spring:
  security:
    user:
      password-encoder: noop
  datasource:
    url: jdbc:mysql://localhost:3306/grade_system
    username: root  # 修改为你的MySQL用户名
    password: 20050116  # 修改为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
server:
  port: 0  # 0表示使用随机可用端口
  servlet:
    context-path: /grade
    
logging:
  level:
    com.grade: DEBUG
    org.springframework.security: DEBUG